FROM alpine AS builder
ARG BIN_DIR
ARG PROJ
ARG ARCH
ADD ${BIN_DIR}/${PROJ}-${ARCH}.tar.xz /
RUN mv /${PROJ} /app

FROM alpine:3.22.1
COPY --from=builder /app /usr/local/bin/
CMD [ "/usr/local/bin/app" ]
