FROM alpine AS builder
ARG BIN_DIR
ARG PROJ
ARG CLI
ARG ARCH
ADD ${BIN_DIR}/${PROJ}-${ARCH}.tar.xz ${BIN_DIR}/${CLI}-${ARCH}.tar.xz /
RUN mv /${PROJ} /app
RUN mv /${CLI} /app-cli

FROM alpine:3.22.0
COPY --from=builder /app /app-cli /usr/local/bin/
CMD [ "/usr/local/bin/app" ]
